 export const productos= [
    {id:1,
    nombre: "Stanley",
    descripción: "Classic Legendary 1L",
    precio: 12000,
    img: 'https://fiskedags.se/2758-tm_large_default/stanley-legendary-classic-flask-1l.jpg',
    cantidad: 1,
    color: "verde",
    },
    {id:2,
    nombre: "Lumilagro",
    descripción: "Luminox 1L - Acero Inox.",
    precio: 5000,
    img: 'https://jumboargentina.vteximg.com.br/arquivos/ids/192108-750-750/Termo-Acero-Inoxidable-Luminox-Lumilagro-X-1-Lt-Termo-Acero-Inoxidable-Luminox-Lumilagro-1-L-1-28460.jpg?v=636383528491800000',
    cantidad: 1,
    color: "gris",
    },
    {id:3,
    nombre: "Stanley",
    descripción: "Clásico negro 1L - Tapón cebador",
    precio: 16000,
    img: 'https://rbimportados.com.py/wp-content/uploads/2020/06/Stanley-classic-Negro-Opaco-15-lts.jpeg',
    cantidad: 1,
    color: "negro",
    },
    {id:4,
    nombre: "Thermos",
    descripción: "King 24hs - Acero inox.",
    precio: 14900,
    img: 'https://www.paris.cl/dw/image/v2/BCHW_PRD/on/demandware.static/-/Sites-cencosud-master-catalog/default/dwa119b8e4/images/imagenes-productos/725/400466-0000-003.jpg?sw=1480&sh=2000&sm=fit',
    cantidad: 1,
    color: "negro",
    },
    {id:5,
    nombre: "Lumilagro",
    descripción: "Luminox Argentina, 1L - Acero Inox.",
    precio: 9000,
    img: 'https://lumilagro.com.ar/wp-content/uploads/2020/12/luminox-banderaargentina-2.jpg',
    cantidad: 1,
    color: "estampado",
    },
    {id:6,
    nombre: "Kovea",
    descripción: "1L - Acero Inox.",
    precio: 11000,
    img: 'https://snond.ir/wp-content/uploads/2020/08/%D9%81%D9%84%D8%A7%D8%B3%DA%A9-1-%D9%84%DB%8C%D8%AA%D8%B1%DB%8C.jpg',
    cantidad: 1,
    color: "negro",
    },
    {id:7,
    nombre: "Vonne",
    descripción: "Tipo bala 1L - Acero Inox.",
    precio: 9000,
    img: 'https://http2.mlstatic.com/D_NQ_NP_2X_788965-MLA47864725279_102021-F.jpg',
    cantidad: 1,
    color: "violeta",
    },
    {id:8,
    nombre: "Stanley",
    descripción: "Adventure blanco 1L - Tapón cebador",
    precio: 25000,
    img: 'https://tatoo.ws/cache/z/article/15007/71005.jpg',
    cantidad: 1,
    color: "blanco",
    },
    {id:9,
    nombre: "Thermos",
    descripción: "Midnight Rojo 1L - Acero Inox.",
    precio: 17400,
    img: 'https://eratukku.fi/tiedostot/67/kuva/tuote/600/187.jpg',
    cantidad: 1,
    color: "rojo",
    },
    {id:10,
    nombre: "Discovery",
    descripción: "Adventures Verde, 1,3L - Acero Inox.",
    precio: 10000,
    img: 'https://http2.mlstatic.com/D_NQ_NP_829230-MLA49897709402_052022-V.jpg',
    cantidad: 1,
    color: "verde",
    },
]
